version: 1.0
listen_port: 9028
debug: false
update_interval_seconds: 20

monitors:
  - directory_name: FILE_EXPORTER
    directory_path: /Users/Username/data/file-count-exporter/
    extensions_to_watch:
      - ".txt"
      - ".py"
      - ".xml"
  - directory_name: DOWNLOADS
    directory_path: /Users/Username/data
    extensions_to_watch:
      - ".txt"
      - ".exe"
